version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    auto-merge: true
    labels:
      - "npm"
      - "dependencies"
    assignees:
      - "Dafnik"
    schedule:
      interval: "monthly"
      time: "08:30"
      timezone: "Europe/Vienna"
    open-pull-requests-limit: 20
    rebase-strategy: all
    commit-message:
      prefix: "[dependabot]"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
