image: timbru31/node-chrome:latest

stages:
  - build
  - deploy

test:
  stage: build
  except:
    - main
  only:
    - branches
  dependencies: []
  artifacts:
    paths:
      - coverage/
  cache:
    paths:
      - node_modules/
  allow_failure: true
  script:
    #    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    #    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    #    - apt-get update -qq && apt-get install -y -qq google-chrome-stable >> /dev/null
    #    - export CHROME_BIN=/usr/bin/google-chrome
    - npm install --loglevel=error --no-progress
    - npm run ngcc # Run npm-script ngcc, if ng build does it, the ci breaks sometimes (not enough memory)
    - npm run helper:test:ci
    - npm run translate:build

build-helper:
  stage: build
  only:
    - /^helper-v.*$/
  except:
    - branches
    - triggers
  artifacts:
    paths:
      - dist/
  cache:
    paths:
      - node_modules/
  script:
    - npm install --loglevel=error --no-progress
    - npm run ngcc # Run ngcc, if ng build does it, the ci breaks sometimes (not enough memory)
    - npm run helper:build
    - cd dist/
    - ls -al

deploy-helper-release-zip:
  stage: deploy
  dependencies:
    - build-helper
  only:
    - /^helper-v.*$/
  except:
    - branches
    - triggers
  cache: {}
  allow_failure: true
  script:
    - apt-get update -qq && apt-get install -y -qq zip git openssh-client >> /dev/null
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - version=$(node -p "require('./projects/dfx-helper/package.json').version")
    - cd dist/
    - zip -r "dfx-helper-${version}.zip" ./dfx-helper >> /dev/null
    - cp "dfx-helper-${version}.zip" dfx-helper-latest.zip
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR ./dfx-helper-latest.zip $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/common/dfx-helper/ > /dev/null
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR "dfx-helper-${version}.zip" $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/common/dfx-helper/ > /dev/null

deploy-helper-release-npm:
  stage: deploy
  allow_failure: true
  dependencies:
    - build-helper
  only:
    - /^helper-v.*$/
  except:
    - branches
    - triggers
  cache: {}
  script:
    - cd dist/dfx-helper/
    - npm config set //registry.npmjs.org/:_authToken ${NPM_PUBLISH_TOKEN}
    - npm publish

build-translate:
  stage: build
  only:
    - /^translate-v.*$/
  except:
    - branches
    - triggers
  artifacts:
    paths:
      - dist/
  cache:
    paths:
      - node_modules/
  script:
    - npm install --loglevel=error --no-progress
    - npm run ngcc # Run ngcc, if ng build does it, the ci breaks sometimes (not enough memory)
    - npm run translate:build
    - cd dist/
    - ls -al

deploy-translate-release-zip:
  stage: deploy
  allow_failure: true
  dependencies:
    - build-translate
  only:
    - /^translate-v.*$/
  except:
    - branches
    - triggers
  cache: {}
  script:
    - apt-get update -qq && apt-get install -y -qq zip git openssh-client >> /dev/null
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - version=$(node -p "require('./projects/dfx-translate/package.json').version")
    - cd dist/
    - zip -r "dfx-translate-${version}.zip" ./dfx-translate >> /dev/null
    - cp "dfx-translate-${version}.zip" dfx-translate-latest.zip
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR ./dfx-translate-latest.zip $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/common/dfx-translate/ > /dev/null
    - scp -P $SSH_PORT -o StrictHostKeyChecking=no -o LogLevel=ERROR "dfx-translate-${version}.zip" $SSH_USERNAME@$SSH_HOST:/var/www/datepoll-share/common/dfx-translate/ > /dev/null

deploy-translate-release-npm:
  stage: deploy
  allow_failure: true
  dependencies:
    - build-translate
  only:
    - /^translate-v.*$/
  except:
    - branches
    - triggers
  cache: {}
  script:
    - cd dist/dfx-translate/
    - npm config set //registry.npmjs.org/:_authToken ${NPM_PUBLISH_TOKEN}
    - npm publish
