import {Inject, Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';

import {Subject} from 'rxjs';
import {TRANSLATE_CONFIG, TranslateConfig} from './translate.config';

export type translationFileType = {[key: string]: string};

@Injectable({
  providedIn: 'root',
})
export class TranslateService {
  translations: translationFileType = {};
  autoGeneratedTranslations: translationFileType = {};

  private selectedLanguage = '';
  public selectedLanguageChange = new Subject<string>();

  defaultLanguage = 'en';
  useLocalStorage = true;
  languagesWithAutoTranslation: string[] = [];
  assetsPath = 'assets/i18n/';

  constructor(private httpClient: HttpClient, @Inject(TRANSLATE_CONFIG) config: TranslateConfig) {
    this.defaultLanguage = config.defaultLanguage ?? this.defaultLanguage;
    this.assetsPath = config.assetsPath ?? this.assetsPath;
    this.useLocalStorage = config.useLocalStorage ?? this.useLocalStorage;
    this.languagesWithAutoTranslation = config.languagesWithAutoTranslation ?? this.languagesWithAutoTranslation;
  }

  public getSelectedLanguage(): string {
    if (this.selectedLanguage.length < 1) {
      const language = this.useLocalStorage ? localStorage.getItem('language') : undefined;
      if (language) {
        console.log('Language cookie found! Using "' + language + '"');
        this.selectedLanguage = language;
        return language;
      } else {
        console.log('No language cookie found! Using "' + this.defaultLanguage + '" as default');
        this.selectedLanguage = this.defaultLanguage;
        return this.defaultLanguage;
      }
    }
    return this.selectedLanguage;
  }

  public translate(key?: string | null): string {
    if (!key) {
      return 'undefined';
    }
    let translation = this.translations[key];
    if (translation) {
      return translation;
    }

    translation = this.autoGeneratedTranslations[key];
    if (translation) {
      return translation;
    }

    return key;
  }

  public use(pickedLanguage?: string): Promise<{}> {
    let lang = '';
    if (pickedLanguage) {
      lang = pickedLanguage;
      this.selectedLanguage = lang;
      this.selectedLanguageChange.next(this.selectedLanguage);
      console.log('Language changed to "' + lang + '"');
      if (this.useLocalStorage) {
        localStorage.setItem('language', lang);
      }
    } else {
      lang = this.getSelectedLanguage();
    }

    return new Promise<translationFileType>((resolve) => {
      this.httpClient.get<translationFileType>(`${this.assetsPath}${this.selectedLanguage}.json`).subscribe({
        next: (translation?) => {
          this.translations = translation;
          resolve(this.translations);
        },
        error: () => {
          this.translations = {};
          resolve(this.translations);
        },
      });

      // Only fetch auto generated translation if there is one
      if (this.languagesWithAutoTranslation.includes(lang)) {
        this.httpClient.get<translationFileType>(`${this.assetsPath}${this.selectedLanguage}_auto.json`).subscribe({
          next: (translation) => {
            this.autoGeneratedTranslations = translation;
            resolve(this.autoGeneratedTranslations);
          },
          error: () => {
            this.translations = {};
            resolve(this.translations);
          },
        });
      }
    });
  }
}
